language: node_js
node_js:
  - '0.10'

install:
  # - npm config set registry http://23.251.144.68
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # Log HTTP requests
  - npm config set loglevel http
  - time npm install

env:
  global:
    - LOGS_DIR=/tmp/rospogeo-map-build/logs

before_script:
  - mkdir -p $LOGS_DIR
  - npm install -g grunt-cli

script:
  - grunt release

after_script:
  - ./src/scripts/travis/print_logs.sh
